version: '3.9'
services:

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    # volumes:
    #   - static_value:/app/static/
    #   - media_value:/app/media/
    # depends_on:
    #   - db
    # env_file:
    #   - ./.env_docker

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
      - frontend

  # db:
  #   image: postgres:15.0
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.env_docker



# volumes:
#   static_value:
#   media_value:
#   postgres_data: